### ISSUE TITLE
AttributeError: module 'linklink' has no attribute 'get_rank'

### ISSUE THREAD

**Issue by yuanbianGit** [hwz-zju/Instruct-ReID#6]
Traceback (most recent call last):
  File "../examples/train_joint.py", line 415, in <module>
    runner.run()
  File "../examples/train_joint.py", line 302, in run
    trainer.train(train_loader, optimizer, lr_scheduler, test_loader, query, gallery)
  File "/data4/by/reid/github/Instruct-ReID-main/reid/trainer/base_trainer.py", line 106, in train
    self._refresh_information(current_iter, lr=lr_scheduler.get_lr()[0])
  File "/data4/by/reid/github/Instruct-ReID-main/reid/trainer/general_trainer.py", line 84, in _refresh_information
    local_rank = link.get_rank() if self.this_task_info else dist.get_rank()
AttributeError: module 'linklink' has no attribute 'get_rank'

**Comment by hwz-zju** [comment]
Thank you for your feedback. 'linklink' is an internal package that is not needed when using our repository. We have updated the version information of the dependency packages. Please try again.

**Comment by yuanbianGit** [comment]
I have adressed this problem. I added the linklink package from https://github.com/huanpengchu/QNCD/tree/6a4e8609f541d433f270ea6a4d7107dbe7141684/linklink, and change the link.get_rank to link.get_local_rank.
